### ISSUE TITLE
Disabling bees causes a crash

### ISSUE THREAD

**Issue by Fr4gtastic** [eerussianguy/firmalife#45]
Setting `beeRarity=0` causes an exception and crashes the game. 

Stacktrace:
`java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.eerussianguy.firmalife.world.WorldgenBees.func_180709_b(WorldgenBees.java:25)
	at com.eerussianguy.firmalife.world.WorldGeneratorFL.generate(WorldGeneratorFL.java:22)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)`
	
Possible solution: an `if` in `WorldgenBees#generate` to check if the config value is not 0, ending the method immediately if it is. Or in `WorldGeneratorFL#generate`, whatever works better.

**Comment by Fr4gtastic** [comment]
Oh, and setting `cinnamonRarity=0` would cause a similar problem.

**Comment by eerussianguy** [comment]
For now just set it to max int
